# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 213a666daf3543f14586b7724369879dc52572b543f06a4a785b49a76eac1570343285db9f94f14e2e86ba70adaf0605371945b8952ffd89af2fd82004ca6bc4

test:
  secret_key_base: 868023fbb533df1dbfb675939a7ab9ffac6b88bbd0c6b9012441cd5a2558f36b2734b1359afdb05386fa7567f757a5bf961b03ae07108d45d1d7ef8140766143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
